### ISSUE TITLE
Plan to have the Billing Web App code updated

### ISSUE THREAD

**Issue by ShubjeetPal** [microsoft/azure-api-management-monetization#33]
I am looking into integrating Azure API management with Stripe for Monetizing API's in our Organization. Is there any plans to update the billing web app code with latest Azure REST API's and libraries. Like I stumbled into @azure/ms-rest-nodeauth is deprecated and should be replaced with @azure/identity
I do not have developers who can take this up.
It will be really helpful if this code is updated with instructions to use it with existing Azure APIM which has Azure AD and B2C users and not use the Authentication (Sign-in & Sign-up) delegation but only use the product subscription delegation.

**Comment by MikeEvansLarah** [comment]
@azure/ms-rest-nodeauth is replaced by @azure/identity in #66
