### ISSUE TITLE
Stripe Demo Setup - az ad sp show doesn't show object id

### ISSUE THREAD

**Issue by karlrissland** [microsoft/azure-api-management-monetization#51]
In strip-deploy.md, after creating a service principle, you are instructed to use the ```az ad sp show --id "<sp id>" to get the object id.  I was unable to find an object id in the response, went to the portal instead.

**Comment by MikeEvansLarah** [comment]
This seems to be due to a change in the underlying `az ad sp show` command.

The object ID can instead be obtained using:

```
az ad sp show --id <application-id> --query '{displayName: displayName, applicationId: appId, objectId: id}'
```
