### ISSUE TITLE
Stripe Demo Deployment - Microsoft.Authorization/RoleAssignments BadRequest

### ISSUE THREAD

**Issue by karlrissland** [microsoft/azure-api-management-monetization#52]
When deploying the Stripe Demo, I receive a Bad Request error type Microsoft.Authorization/roleAssignments.

![image](https://github.com/microsoft/azure-api-management-monetization/assets/9871029/30212248-a121-426f-8df1-c9f4e9c58a5b)

**Comment by MikeEvansLarah** [comment]
This looks like you may have used the object ID of the Application instead of the object ID of the Service Principal as the `servicePrincipalObjectId` object.

See my response in #51 - I've updated the documentation to show how to get the correct the object ID.
