### ISSUE TITLE
stripe: parameter_unknown - "recurring Received unknown parameter: "recurring. Did you mean recurring?

### ISSUE THREAD

**Issue by frouhi** [microsoft/azure-api-management-monetization#57]
I followed the stripe-deploy.md step by step, but I see the above error in the product page in stripe. Seems like an obvious typo somewhere. I'm wondering if anyone else has come across this bug and if there is a known fix for it?

some more details:
this seems to be the post body for this endpoint (POST /v1/prices)
````
{
  ""recurring": {
    "interval": {
      """: "month"
    },
    "usage_type": {
      """: "licensed"
    },
    "interval_count": {
      """: "1"
    }
  },
  "product": ["basic"](https://dashboard.stripe.com/test/products/basic),
  "currency": "usd",
  "unit_amount_decimal": "1495"
}
````
Thanks

**Comment by frouhi** [comment]
actually, a similar issue is happening in other api calls to stripe as well!

<img width="497" alt="Screenshot 2023-09-09 at 2 06 18 PM" src="https://github.com/microsoft/azure-api-management-monetization/assets/34617952/0db1238d-a4d3-4f57-b1ee-350c97fbae4e">

**Comment by frouhi** [comment]
Another issue I'm having is that when I create a product through the dashboard, it doesn't get added to the stripe products. (and I don't know how to do it manually because I can't add the product ID manually from the stripe dashboard when trying to create it there).

**Comment by rishabhdugar** [comment]
more similar error response from stripe dashboard
{
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameters: \"tiers, \"recurring. Did you mean tiers or recurring?",
    "param": "\"tiers",
    "request_log_url": "https://dashboard.stripe.com/test/logs/req_kwKuJ6a9as4YrQ?t=1696351661",
    "type": "invalid_request_error"
  }
}
