### ISSUE TITLE
TypeScript errors in app build

### ISSUE THREAD

**Issue by MikeEvansLarah** [microsoft/azure-api-management-monetization#61]
Following errors when running `npm run build`:

```
#10 7.556 src/services/apimService.ts(133,34): error TS2339: Property 'id' does not exist on type 'unknown'.
#10 7.557 src/services/monetizationService.ts(14,54): error TS2339: Property 'find' does not exist on type 'unknown'.
```

**Comment by joelbudu** [comment]
@MikeEvansLarah how is it looking with the updates to the app please? Will there be an update to the container image at mcr.microsoft.com/azure-api-management/samples/monetization ? Thanks

**Comment by HowardvanRooijen** [comment]
I believe we were waiting on @mikebudzynski

**Comment by MikeEvansLarah** [comment]
There has been a new version of the app published with the latest updates as of last month
mcr.microsoft.com/azure-api-management/samples/monetization:0.2.0

**Comment by joelbudu** [comment]
Sounds great @MikeEvansLarah, Thank you.
I think it might be good also to update the main.bicep accordingly so the old image is not used when a deployment is made

**Comment by MikeEvansLarah** [comment]
@joelbudu it's been updated now in #71

**Comment by joelbudu** [comment]
Thanks @MikeEvansLarah
