### ISSUE TITLE
Billing Portal Update

### ISSUE THREAD

**Issue by azep-ninja** [microsoft/azure-api-management-monetization#62]
Hello, are there any plans to upgrade the Billing Portal App?

Using the current version seems is now broken and does not work. I am able to get the products registered but upon trying to Subscribe, users get a white screen like if its having issues with the Stripe checkout sessions, packages seem to be outdated, typscript errors.

Has anyone been able to get this workin recently?

**Comment by HowardvanRooijen** [comment]
We've applied a series of updates - if you deploy latest it should work, but please provide any feedback is you still have issues.
